export const profiles = [
    {   id: 1,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 2,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 3,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 4,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 5,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 6,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 7,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 8,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'pending'
    },
    {   id: 9,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'complete'
    },
    {   id: 10,
        name: 'Brookln Simmons',
        date: '05 april 2023',
        time: '10:50 AM',
        lab: '15687-456',
        refer: 'Dr. Anupama rai',
        from: 'LAB',
        price: 254,
        status: 'complete'
    },
]